#ifndef TELEIOS_WINDOW_EVENTCODES_H
#define TELEIOS_WINDOW_EVENTCODES_H

#define TL_EVENT_WINDOW_CREATED         240
#define TL_EVENT_WINDOW_SHOWED          241
#define TL_EVENT_WINDOW_HIDDEN          242
#define TL_EVENT_WINDOW_MAXIMIZED       243 // u32[0, 1]
#define TL_EVENT_WINDOW_MINIMIZED       244 // u32[0, 1]
#define TL_EVENT_WINDOW_MOVED           245 // i32[0, 1]
#define TL_EVENT_WINDOW_RESIZED         246 // u32[0, 1]
#define TL_EVENT_WINDOW_RESTORED        247 // u32[0, 1]
#define TL_EVENT_WINDOW_FOCUS_GAINED    248
#define TL_EVENT_WINDOW_FOCUS_LOST      249
#define TL_EVENT_WINDOW_CLOSED          250

#endif // TELEIOS_WINDOW_EVENTCODES_H