#ifndef TELEIOS_INPUT_KEYBOARD_EVENT_H
#define TELEIOS_INPUT_KEYBOARD_EVENT_H

#define TL_EVENT_INPUT_KEY_PRESSED      230 // u16[0]
#define TL_EVENT_INPUT_KEY_RELEASED     231 // u16[0]

#endif // TELEIOS_INPUT_KEYBOARD_EVENT_H