#ifndef TELEIOS_EVENT_CODES_H
#define TELEIOS_EVENT_CODES_H

#include "teleios/types.h"

typedef enum {
    TL_EVENT_WINDOW_RESIZED = 210, // u32[0, 1]
    TL_EVENT_WINDOW_MINIMIZED, // Null
    TL_EVENT_WINDOW_MAXIMIZED, // Null
    TL_EVENT_WINDOW_RESTORED, // Null
    TL_EVENT_WINDOW_FOCUS_GAINED, // Null
    TL_EVENT_WINDOW_FOCUS_LOST, // Null
    TL_EVENT_WINDOW_MOVED, // i32[0, 1]

    TL_EVENT_INPUT_MOUSE_MOVE = 220, // i32[0 ,1]
    TL_EVENT_INPUT_MOUSE_WHELL, // i8[0]
    TL_EVENT_INPUT_MOUSE_PRESSED, // u8[0]
    TL_EVENT_INPUT_MOUSE_RELEASED, // u8[0]
    TL_EVENT_INPUT_MOUSE_LEAVE, // Null
    TL_EVENT_INPUT_MOUSE_ENTER, // i32[0 ,1]
    TL_EVENT_INPUT_KEY_PRESSED, // u16[0]
    TL_EVENT_INPUT_KEY_RELEASED, // u16[0]

    TL_EVENT_MAXIMUM = U8MAX

} TLEventCodes;


#endif // TELEIOS_EVENT_CODES_H
