#ifndef TELEIOS_INPUT_MOUSE_EVENT_H
#define TELEIOS_INPUT_MOUSE_EVENT_H

#define TL_EVENT_INPUT_MOUSE_PRESSED    232 // u8[0]
#define TL_EVENT_INPUT_MOUSE_RELEASED   233 // u8[0]
#define TL_EVENT_INPUT_MOUSE_MOVED      234 // i32[0, 1]
#define TL_EVENT_INPUT_MOUSE_SCROLLED   235 // i8[0]

#endif // TELEIOS_INPUT_MOUSE_EVENT_H