#ifndef TELEIOS_INPUT_MOUSE_KEYCODE_H
#define TELEIOS_INPUT_MOUSE_KEYCODE_H

typedef enum {
    TL_MOUSE_LEFT,
    TL_MOUSE_RIGHT,
    TL_MOUSE_MIDDLE,
    TL_MOUSE_MAXIMUM
} TLInputMouse;

#endif // TELEIOS_INPUT_MOUSE_KEYCODE_H
